<ol>
    <h1>Упражнение 1 - Numpy</h1>
    <li>Пусть у двух матриц совпадает количество строк. Объедините их в одну горизонтально (объедините столбцы этих матриц)</li>
    <li>Пусть дана пuтру-матрица $M$ и два массива индексов $a, b$ одинаковой длины. Постройте массив элементов $M[a[0],b[0]], M[a[1],b[1]],\dots$ Указание: для выполнения этой операции не требуется никаких именных функций.</li>
    <li>Подсчитайте след матрицы и количество ненулевых элементов на ее диагонали</li>
    <li>Даны два произвольных numpy-массива одинаковой размерности $(n,m)$. Замените нулями те элементы второго массива, для которых на соответствующем месте в первом массиве находятся отрицательные числа</li>
    <li>Даны две матрицы с одинаковым количеством строк и количеством столбцов $n$ и $m$ соответственно. Постройте матрицу
всевозможных произведений столбцов друг на друга (в смысле скалярного произведения).</li>
</ol>
<hr>

In [1]:
import numpy as np

In [2]:
#Ex 1.1

A = np.zeros((3,4))
B = np.ones((3,7))

C = np.concatenate((A, B), axis = 1)
print(C)

[[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]]


In [3]:
#Ex 1.2

M = np.random.randint(low = 0, high = 10, size = (5, 7))
a = np.random.randint(low = 0, high = 5, size = 6)
b = np.random.randint(low = 0, high = 7, size = 6)

print("M\n", M)
print("a\n", a)
print("b\n", b)
print("M[a,b]\n", M[a,b])

M
 [[8 2 3 4 6 8 6]
 [9 5 2 4 5 0 8]
 [3 2 5 8 4 2 1]
 [8 6 3 7 4 0 3]
 [2 3 6 7 1 3 4]]
a
 [0 2 0 3 0 1]
b
 [6 4 5 3 1 2]
M[a,b]
 [6 4 8 7 2 2]


In [4]:
#Ex 1.3

N = np.random.randint(low = -3, high = 4, size = (5, 7))
tr = np.trace(N)
Dg = np.diag(N)
n = np.count_nonzero(Dg)

print("N:\n", N)
print("Trace:", tr)
print("Non-zero diag elements:", n)

N:
 [[-2  1 -3 -1  3  1  0]
 [-2  3 -2 -3 -2 -2 -2]
 [ 0 -3  0  0  2  0 -1]
 [ 3 -1  1  1  0 -2 -1]
 [-2 -3  1  3 -2 -1  3]]
Trace: 0
Non-zero diag elements: 4


In [5]:
#Ex 1.4

n, m = 5, 7

A = np.random.randint(low = 0, high = 2, size = (n, m))
B = np.random.randint(low = 1, high = 4, size = (n, m))
print("A:\n", A)
print("B:\n", B)

B[A == 0] = 0
print("B[A == 0]:\n", B)

A:
 [[0 0 0 0 0 0 1]
 [1 0 0 1 0 1 1]
 [1 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [1 0 1 0 1 0 1]]
B:
 [[1 2 1 1 3 2 1]
 [2 2 1 2 3 2 2]
 [2 1 2 3 3 2 3]
 [1 2 2 2 1 2 2]
 [1 1 1 3 2 2 3]]
B[A == 0]:
 [[0 0 0 0 0 0 1]
 [2 0 0 2 0 2 2]
 [2 1 0 0 0 0 0]
 [0 0 0 0 0 2 0]
 [1 0 1 0 2 0 3]]


In [6]:
#Ex 1.5

n, m = 5, 7

A = np.random.randint(low = -3, high = 4, size = (n, m))
B = np.random.randint(low = -3, high = 4, size = (n, m))
print("A:\n", A)
print("B:\n", B)

C = np.zeros((m, m), dtype = np.int32)
for i in range(m):
    for j in range(m):
        C[i, j] = np.dot(A[:, i], B[:, j])

print("A*B\n", C)

A:
 [[-2  2 -2  3 -2  3 -2]
 [-3 -2  3  0 -2  3  3]
 [-1 -3  0 -2 -2 -3 -3]
 [-1  2  1  3  3 -2  1]
 [ 1 -3 -3 -1 -1  0  3]]
B:
 [[-2 -1  0  3  2 -2  0]
 [ 1  3  0  3 -2  3 -1]
 [ 0  2  2  2 -2  0 -2]
 [-2 -1 -1  2  0  2  3]
 [ 0 -1  2 -3  3 -2  3]]
A*B
 [[  3  -9   1 -22   7  -9   5]
 [-10 -13 -14   7   5   0   5]
 [  5  13  -7  14 -19  21  -9]
 [-12  -9  -9  14   7   2  10]
 [ -4 -10  -9  -7   1   6  12]
 [  1   2  -4   8   6  -1  -3]
 [  5   1  -1 -10   5   9  15]]
